const main = async () => {
  throw new Error('oops');
};

main();
